[package]
authors = ["Cameron Eldridge <cameldridge@gmail.com>"]
edition = "2018"
name = "rpg"
version = "0.1.0"
[dependencies]
crossbeam-channel = "0.5"
legion = "0.4"
log = "0.4"
pancurses = "0.16"
paw = "1.0"
pretty_env_logger = "0.4"

[dependencies.structopt]
features = ["paw"]
version = "0.3"
